### ISSUE TITLE
Discrepancy in the Risk Distortion and GPU Support

### ISSUE THREAD

**Issue by Shentao-YANG** [nuria95/O-RAAC#1]
Hi,

Thanks for providing this interesting package. 

We are very interesting in your paper *Risk-Averse Offline Reinforcement Learning* and would like to replicate the results therein. However, I encounter two problem in trying to replicate the results.

1.  In the two of the json files at `O-RAAC/json_params/ORAAC/` (`Params_cheetah_expert.json` and `Params_cheetah_medium.json`) you have `"RISK_DISTORTION": "wang"`, on other json files you have `"RISK_DISTORTION": "cvar"`.  However, in your paper you use CVaR_{0.1} as the risk measure. May I ask whether I should replace the two `"RISK_DISTORTION": "wang"` with `"RISK_DISTORTION": "cvar"` as in other four json files? Are there any other parameters in the json files that we need to change in order to replicate Table 2 in your paper ?

2. Does this package support training the model with GPU? I do see a line of code `parser.add_argument('--device', action="store", type=str)` in `O-RAAC/utils/utilities.py/` but this argument seems used nowhere. I try to run you code in a GPU server using the command `python3.8 oraac.py --device "cuda:0" --config_name 'Params_cheetah_medium.json'` and the GPU seems **NOT** used. (I move the oraac.py file out from the `experiments` folder).  Could you please let me know how did you train the models using GPUs.

**Comment by nuria95** [comment]
Hi @Shentao-YANG ,
Thanks a lot for the interest in our package and paper!

1. I uploaded some json files with the parameter "RISK_DISTORTION" set to "wang" and some others set to "cvar" to show that the algorithm (and hence the code is set for that too) can optimize different risk distortions (i.e Wang criteria or Conditional Value at Risk (CVaR) respectively). In the Table 2 in our paper we show results optimizing the CPW risk distortion and the CVaR  with confidence levels 0.1 and 0.25 . In order to replicate the results, to optimize for the CPW you need to set `"RISK_DISTORTION": "cpw"`  and to optimize for the CVaR you need to set `"RISK_DISTORTION": "cvar"` and `"alpha_level": 0.1` and `"alpha_level": 0.25`  respectively. We didn't provide the results optimizing the Wang risk distortion in the paper due to lack of space.
2. Regarding the GPU usage, the package as it is doesn't support GPU usage at the moment, so unfortunately I cannot help regarding that part. We didn't use it for our results in the paper either.

Hope that helps you!
